using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public class MapGenerationHandler : MonoBehaviour
{
    List<Tile> _tileMatrix = new();
    List<Biome> _generatedBiomes = new();
    [SerializeField] MapGenerationConfig _generationConfig;
    public List<Tile> TileMatrix { get { return _tileMatrix; } }

    static MapGenerationHandler instance;
    public static MapGenerationHandler mgh {  get { return instance; } }
    private void Awake()
    {
        instance = this;
    }
    private void Start()
    {
        //WaveManager.wm.OnWaveStarted += WaveStarted;
    }
    void WaveStarted()
    {
        if(WaveManager.wm.CurrWave % _generationConfig.WavesBetweenGenerations == 0)
            GenerateBiome();
    }
    public void GenerateBiome()
    {
        int biomeSize = (int)_generationConfig.BiomeSize.rand;

        //Get side where the biome will be generated
        var biomeGenerationInfo = GetBiomeGenerationInfo(new(biomeSize, biomeSize));

        BiomeData generatedBiomeData = GetGeneratedBiome();
        Biome generatedBiome = new Biome(generatedBiomeData);

        //get the tiles generated by the biome
        var newBiomeTiles = generatedBiome.GenerateBiomeTiles(biomeGenerationInfo);
        _tileMatrix.AddRange(newBiomeTiles);

        //set the tiles generated by the biome and the intersecting tiles
        newBiomeTiles.Concat(biomeGenerationInfo.intersectingTiles);
        foreach(var tile in newBiomeTiles)
        {
            tile.SetTileGfx();
        }

        //generate random obstacles in the biome tiles (maybe with support objs?)
        //store the biome
        _generatedBiomes.Add(generatedBiome);
    }

    BiomeGenerationInfo GetBiomeGenerationInfo(Vector2 biomeSize)
    {
        List<Tile> wallTiles = new List<Tile>();
        foreach (var biome in _generatedBiomes)
        {
            wallTiles.AddRange(biome.Walls);
        }
        List<BiomeGenerationInfo> placeableTiles = new List<BiomeGenerationInfo>();

        foreach (var tile in wallTiles)
        {
            print("There are wall tiles");
            var placeableDirections = CanBePlacedAt(tile.transform.position, biomeSize, wallTiles);
            foreach (var direction in placeableDirections)
            {
                Vector2 startingPoint = tile.transform.position;
                if (direction.x < 0)
                    startingPoint -= Vector2.right * biomeSize.x;
                if (direction.y < 0)
                    startingPoint -= Vector2.up * biomeSize.y;

                var intersectingTiles = GetBiomeIntersectionTiles(startingPoint, biomeSize, wallTiles);

                placeableTiles.Add(new(tile.transform.position, direction, biomeSize, intersectingTiles, startingPoint));
            }
        }

        var generationInfo = placeableTiles.Count == 0 ? new(-biomeSize / 2, new Vector2(1, 1), biomeSize, new(), -biomeSize / 2) : placeableTiles[Random.Range(0, placeableTiles.Count)];
        return generationInfo;
    }

    List<Vector2> CanBePlacedAt(Vector2 position, Vector2 size, List<Tile> wallTiles)
    {
        List<Vector2> possibleDirections = BiomeGenerationInfo.allDirections;
        List<Vector2> possibleDirsCopy = new List<Vector2>(possibleDirections);
        foreach (var dir in possibleDirsCopy)
        {
            for (int x = (int)dir.x; Mathf.Abs(x) < size.x; x += (int)dir.x)
            {
                for (int y = (int)dir.y; Mathf.Abs(y) < size.y; y += (int)dir.y)
                {
                    var newTilePos = position + new Vector2(x, y);
                    if (wallTiles.Exists(tile => (Vector2)tile.transform.position == newTilePos))
                        possibleDirections.Remove(dir);
                }
            }

        }
        return possibleDirections;
    }

    List<Tile> GetBiomeIntersectionTiles(Vector2 startingPoint, Vector2 biomeSize, List<Tile> wallTiles)
    {
        List<Tile> intersectingTiles = new List<Tile>();
        for (int y = 0; y <= biomeSize.y; y++)
        {
            Vector2 intersectingBottomPos = new Vector2(0, y);
            Vector2 intersectingTopPos = new Vector2(biomeSize.x, y);

            Tile intersectingTileBottom = wallTiles.Find(tile => (Vector2)tile.transform.position == intersectingBottomPos);

            Tile intersectingTileTop = wallTiles.Find(tile => (Vector2)tile.transform.position == intersectingTopPos);

            if (intersectingTileBottom != null)
                intersectingTiles.Add(intersectingTileBottom);
            if (intersectingTileTop != null)
                intersectingTiles.Add(intersectingTileTop);
        }
        for (int x = 0; x <= biomeSize.x; x++)
        {
            Vector2 intersectingLeftPos = new Vector2(x, 0);
            Vector2 intersectingRightPos = new Vector2(x, biomeSize.y);

            Tile intersectingTileLeft = wallTiles.Find(tile => (Vector2)tile.transform.position == intersectingLeftPos);

            Tile intersectingTileRight = wallTiles.Find(tile => (Vector2)tile.transform.position == intersectingRightPos);

            if (intersectingTileLeft != null)
                intersectingTiles.Add(intersectingTileLeft);
            if (intersectingTileRight != null)
                intersectingTiles.Add(intersectingTileRight);
        }
        return intersectingTiles;
    }

    BiomeData GetGeneratedBiome()
    {
        List<BiomeData> possibleBiomes = new(_generationConfig.PossibleBiomes);
        List<BiomeData> existingBiomes = new();
        foreach (var biome in _generatedBiomes)
        {
            if (existingBiomes.Contains(biome.BiomeData))
                continue;
            existingBiomes.Add(biome.BiomeData);
        }
        if (existingBiomes.Count != possibleBiomes.Count) //NOT all biomes have been generated once, remove the ones that do
            possibleBiomes.RemoveAll(x => existingBiomes.Contains(x));

        return possibleBiomes[Random.Range(0, possibleBiomes.Count)];
    }
}
