using System.Collections;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using UnityEngine;
using UnityEngine.UIElements;

[System.Serializable]
public class MapGenerationHandler
{
    [SerializeField] Transform _tileHolder;
    Dictionary<Vector2, List<Tile>> _tileMatrix = new();
    List<Biome> _generatedBiomes = new();
    public Dictionary<Vector2, List<Tile>> TileMatrix { get { return _tileMatrix; } }

    public BiomeUpdateInstance GenerateBiome()
    {
        int biomeSize = (int)MapManager.mm.GenerationConfig.BiomeSize.rand;

        //Get side where the biome will be generated
        var biomeGenerationInfo = GetBiomeGenerationInfo(new(biomeSize, biomeSize));

        BiomeData generatedBiomeData = GetGeneratedBiome();
        Biome generatedBiome = new Biome(generatedBiomeData);

        //get the tiles generated by the biome
        List<Tile> newBiomeTiles = new(generatedBiome.GenerateBiomeTiles(biomeGenerationInfo));
        foreach(var tile in newBiomeTiles)
        {
            tile.transform.parent = _tileHolder;
            Vector2 tilePos = tile.transform.position;
            if (_tileMatrix.ContainsKey(tilePos))
                _tileMatrix[tilePos].Add(tile);
            else
                _tileMatrix.Add(tilePos, new() { tile });
        }

        //set the tiles generated by the biome and the intersecting tiles
        var updatedTiles = newBiomeTiles.Concat(biomeGenerationInfo.intersectingTiles).ToList();

        //generate random obstacles in the biome tiles (maybe with support objs?)
        //store the biome
        _generatedBiomes.Add(generatedBiome);
        GameProgressionManager.gpm.AddBosses(generatedBiomeData.BiomeBosses.Count);

        BiomeUpdateInstance biomeUpdateInstance = new BiomeUpdateInstance(updatedTiles, generatedBiome);

        return biomeUpdateInstance;
    }

    BiomeGenerationInfo GetBiomeGenerationInfo(Vector2 biomeSize)
    {
        if (_generatedBiomes.Count == 0)
        {
            BiomeGenerationInfo noSidegenerationInfo = new(-biomeSize / 2, new Vector2(1, 1), biomeSize, new(), -biomeSize / 2);
            return noSidegenerationInfo;

        }
        BiomeSide chosenSide = null;
        List<Biome> biomesCopy = new List<Biome>(_generatedBiomes);
        bool biomeGenerated = false;
        while(!biomeGenerated)
        {
            Biome randBiome = biomesCopy[Random.Range(0, _generatedBiomes.Count)];
            List<Vector2> biomeDirections = new()
            {
                new Vector2(1, 0),
                new Vector2(0, 1),
                new Vector2(0, -1),
                new Vector2(-1, 0)
            };
            biomeDirections = Utility.ShuffleList(biomeDirections);
            for(int i = 0; i < biomeDirections.Count; i++)
            {
                Vector2 randDir = biomeDirections[Random.Range(0, biomeDirections.Count)];
                BiomeSide randSide = randBiome.GetSide(randDir);
                if (CanBePlacedAt(randSide, biomeSize))
                {
                    chosenSide = randSide;
                    biomeGenerated = true;
                    break;
                }
            }
        }
        Vector2 generationStartPos = chosenSide.sideStartPos;
        if (chosenSide.generationDir.x < 0)
            generationStartPos.x -= biomeSize.x;
        if (chosenSide.generationDir.y < 0)
            generationStartPos.y -= biomeSize.y;

        var intersectingTiles = GetBiomeIntersectionTiles(generationStartPos, biomeSize);
        BiomeGenerationInfo sideGenerationInfo = new(chosenSide.sideStartPos, chosenSide.generationDir, biomeSize, intersectingTiles, generationStartPos);
        return sideGenerationInfo;
    }

    bool CanBePlacedAt(BiomeSide placingSide, Vector2 size)
    {
        var dir = placingSide.generationDir;
        var position = placingSide.sideStartPos;
        for (int x = (int)dir.x; Mathf.Abs(x) < size.x; x += (int)dir.x)
        {
            for (int y = (int)dir.y; Mathf.Abs(y) < size.y; y += (int)dir.y)
            {
                var newTilePos = position + new Vector2(x, y);
                if (_tileMatrix.ContainsKey(newTilePos)) 
                    return false;
            }
        }
        return true;
    }
    List<Tile> GetBiomeIntersectionTiles(Vector2 startingPoint, Vector2 biomeSize)
    {
        List<Tile> intersectingTiles = new List<Tile>();
        for (int y = 0; y <= biomeSize.y; y++)
        {
            Vector2 intersectingLeftOffset = new Vector2(0, y);
            Vector2 intersectingRightOffset = new Vector2(biomeSize.x, y);

            Vector2 intersectingLeftPos = startingPoint + intersectingLeftOffset;
            Vector2 intersectingRightPos = startingPoint + intersectingRightOffset;

            if(_tileMatrix.ContainsKey(intersectingLeftPos))
                intersectingTiles.AddRange(_tileMatrix[intersectingLeftPos]);
            if (_tileMatrix.ContainsKey(intersectingRightPos))
                intersectingTiles.AddRange(_tileMatrix[intersectingRightPos]);
        }
        for (int x = 0; x <= biomeSize.x; x++)
        {
            Vector2 intersectingBottomOffset = new Vector2(x, 0);
            Vector2 intersectingTopOffset = new Vector2(x, biomeSize.y);

            Vector2 intersectingBottomPos = startingPoint + intersectingBottomOffset;
            Vector2 intersectingTopPos = startingPoint + intersectingTopOffset;

            if (_tileMatrix.ContainsKey(intersectingBottomPos))
                intersectingTiles.AddRange(_tileMatrix[intersectingBottomPos]);
            if (_tileMatrix.ContainsKey(intersectingTopPos))
                intersectingTiles.AddRange(_tileMatrix[intersectingTopPos]);
        }
        return intersectingTiles;
    }

    BiomeData GetGeneratedBiome()
    {
        List<BiomeData> possibleBiomes = new(MapManager.mm.GenerationConfig.PossibleBiomes);
        List<BiomeData> existingBiomes = new();
        foreach (var biome in _generatedBiomes)
        {
            if (existingBiomes.Contains(biome.BiomeData))
                continue;
            existingBiomes.Add(biome.BiomeData);
        }
        if (existingBiomes.Count != possibleBiomes.Count) //NOT all biomes have been generated once, remove the ones that do
            possibleBiomes.RemoveAll(x => existingBiomes.Contains(x));

        return possibleBiomes[Random.Range(0, possibleBiomes.Count)];
    }
}
